ideamon/config/routes.rb
Rails.application.routes.draw do

  resources :questions
  get "projects/home"
  get "projects/about"
  get "ideas/start"
  get "projects/help"
  get "projects/impressum"
  

  devise_for :users
  resources :creativitycards 
  resources :projects 
  resources :ideas 

   

  root 'projects#home'

end

ideamon/app/models/project.rb
class Project < ActiveRecord::Base


	belongs_to :user
	has_many :ideas
	has_many :creativitycards

	validates :name, :deadline, :question, presence: true
	validates :name, uniqueness: true

	accepts_nested_attributes_for :creativitycards, 
  		allow_destroy: true, 
      :reject_if => :all_blank

	def is_delayed?
	 self.deadline < Date.today
	end

	def distance_from_now_in_days
	  (self.deadline - Date.today).to_i     
	end

	def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |projects|
        csv << projects.attributes.values_at(*column_names)
      end
    end
  end
	
end

ideamon/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_project_admin_edit_destroy, only: [:edit, :update, :destroy]
  before_action :set_project_admin_create, only: [:new, :create]
  before_action :set_user, only: [:help]
  before_action :authenticate_user!, except: [:home, :about, :help, :impressum]

  # GET /projects
  # GET /projects.json
  def home
  end

  def about
  end

  def help
  end

  def impressum
    
  end
  
  def index
    @projects =Project.all
    
    if params[:sorting]
      @done = Project.where("done = ? OR deadline < ?", true, Date.today).order(params[:sorting] => :asc)
      @todo = Project.where("done = ? AND deadline >= ?", false, Date.today).order(params[:sorting] => :asc)
    else 
      @done = Project.where("done = ? OR deadline < ?", true, Date.today).order(deadline: :desc)     
      @todo = Project.where("done = ? AND deadline >= ?", false, Date.today).order(deadline: :asc)
    end

    if current_user.admin != true
      redirect_to :root, alert: 'Only for Admins!'
    end

    respond_to do |format|
      format.html
      format.csv { send_data @projects.to_csv }
      format.xls
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @ideas = Idea.all
    @userprojects = current_user.projects.all
    @userideas = Project.find(params[:id]).ideas
    @idea = Idea.new
    @creativitycards = Creativitycard.all
    @projectccard = Project.find(params[:id]).creativitycards
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.ideas.build
    @project.creativitycards.build
  end

  # GET /projects/1/edit
  def edit   
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def set_project_admin_edit_destroy
      @project = Project.find(params[:id])
      if @project.user_id != current_user.id || current_user.admin != true
        redirect_to :back, alert: 'Only Admin are alowd to edit or delete Projects/ You can only change your own Project.'
      end
    end

    def set_project_admin_create
      @project = Project.new
      
      if current_user.admin != true
        redirect_to :back, alert: 'Only Admin are alowd to create Projects.'
      end
    end

    def set_user
       @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :deadline, :done, :question, :comment, :user_id, creativitycards_attributes: [:id, :title, :suggestion, :example, :shortdescription,  :image, :remote_image_url, :idea_id, :project_id, :user_id,  :_destroy])
    end
end

ideamon/app/helpers/projects_helper.rb
module ProjectsHelper
end

ideamon/app/views/projects/_form.html.erb
<%= nested_form_for @project, :html => { :multipart => true} do |f| %> 


  <% if @project.errors.any? %>
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="checkbox">
    <label>
      <%= f.check_box :done %> <%= f.label :done %>
    </label>
  </div>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "Name of Project" %>
  </div>
  <div class="form-group">
    <%= f.label :deadline %><br>
    <%= f.date_field :deadline, class: "form-control", placeholder: "Deadline of Project" %>
  </div>
  <div class="form-group">
    <%= f.label :question %><br>
    <%= f.text_field :question, class: "form-control", placeholder: "Question for Brainstorming" %>
  </div>
  <div class="form-group">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, class: "form-control", placeholder: "some description" %>
  </div>

  <div class="form-group"> 
    <%= f.fields_for :creativitycards do |builder| %>
    <%= render 'kreativismen', f: builder %>
    <% end %>
    </br>
    <p><%= f.link_to_add "Add more Kreativismen", :creativitycards, class: "btn btn-success btn-sm" %></p>
  </div>   

  <div class="actions">
    <%= f.submit "Save Project", class: "btn btn-primary" %>  
    <%= link_to 'Back to Project overview', projects_path, class: "btn btn-default" %>
  </div> 
<% end %>

ideamon/app/views/projects/_info.html.erb
<div class="panel panel-info">
  <div class="panel-body">
    <p>
    <strong>Name:</strong>
      <%= @project.name %>
    </p>

    <p style="white-space: pre-line;">
      <strong>Comment:</strong>
      <%= @project.comment %>
    </p>

    <p>
      <strong>Deadline:</strong>
      <%= @project.deadline %>
    </p>

    <table class="table">
      <thead>
        <tr>
          <td colspan="3"></td>
        </tr>
      </thead>

      <tbody>
          <tr>
            <% if current_user.admin == true %>
              <td>

                <%= form_for @project do |f| %>
                <strong>done?  </strong><%= f.check_box :done, class: "checkable" %>
                <% end %>
              </td>            
            <td><%= link_to 'Back to Project overview', projects_path, class: "btn btn-primary btn-sm" %></td>
            <td><%= link_to 'Edit', edit_project_path(@project), class: "btn btn-warning btn-sm" %></td>
            <td><%= link_to 'Destroy', @project, class: "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% else %>
            <td><%= link_to 'Back to Project overview', ideas_start_path, class: "btn btn-primary btn-sm" %></td>
            <% end %>

          </tr>
      </tbody>
    </table>

  </div>
</div>  

ideamon/app/views/projects/_myProjects.html.erb
<div class="row">
  <% @userprojects.each do |project| %>
  

      <div class="panel panel-success">             
        <div class="panel-body">                          
          <p>        
            <%= project.name %>
          </p>                
        </div>
      </div>                  
  
  <% end %>
</div>

ideamon/app/views/projects/_projecttable.html.erb
<table class="table table-striped table-bordered table-hover "> 
  <thead>
    <tr>
      <% if current_user.admin == true %>
        <th>Done?</th>
        <% else %>
      <% end %>
      <th>
      <% if params[:sorting] == "name" %>
        Name
      <% else %>
        <%= link_to "Name", projects_path(sorting: "name") %>
      <% end %>
      </th>
      <th>
      <% if params[:sorting] == "deadline" %>
        Deadline
      <% else %>
        <%= link_to "Deadline", projects_path(sorting: "deadline") %>
      <% end %>
      </th>
      <th>
      <% if params[:sorting] == "question" %>
        Question
      <% else %>
        <%= link_to "Question", projects_path(sorting: "question") %>
      <% end %> 
      </th>
    </tr>
  </thead>

  <tbody>
    <% projects.each do |project| %>
      <tr >
        <% if current_user.admin == true %>
          <td>
          <%= form_for project do |f| %>
          <%= f.check_box :done, class: "checkable" %>
          <% end %>
          </td>
          <% else %>
        <% end %>        
        <td class="<%= css_class %>"><%= link_to project.name, project_path(project) %></td>
        <td>
          <%= "in " if !project.is_delayed? %> 
          <%= pluralize(project.distance_from_now_in_days.abs, "Day")  %>
          <%= " ago " if project.is_delayed? %>
          (<%= project.deadline %>) 
        </td>
        <td><%= project.question %></td>                  
      </tr>
    <% end %>
  </tbody>
</table>

ideamon/app/views/projects/_tab_allIdeas.html.erb
</br>

<div class="row">
  <% @project.ideas.order("RANDOM()").each do |idea| %>
  <div class="col-md-4">
    <div class="thumbnail" id="thumb">                          
      <%= link_to idea.post, edit_idea_path(idea) %>            
    </div>                  
  </div>
  <% end %> 
</div>


ideamon/app/views/projects/_tab_myIdeas.html.erb
</br>

<div class="row">
  <% @userideas.order(created_at: :desc).each do |idea| %>
    <% if idea.user_id == current_user.id %>
      <div class="col-md-4">
        <div class="thumbnail" id="thumb">                                           
          <%= link_to idea.post, edit_idea_path(idea) %>                                   
        </div>
      </div> 
      <% else %>                 
    <% end %>
  <% end %>
</div>

ideamon/app/views/projects/about.html.erb

<div class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">

      <div class="page-header">          
        <h1> About </h1>
      </div>

      <div class="col-md-3" id="leftCol">
        <div class="thumbnail">     
          <%= image_tag ("Imon.jpg") %> 
          <h2>MaiMon :-) <small>bedankt sich ganz herzlich bei allen Teilnehmern ♥♥♥</small> </h2>
        </div>
      </div>     

      <div class="col-md-9" id="rightCol"> 
        <div class="well">  
          <div class="panel panel-primary">
            <div class="panel-body">      
              <ul class="nav nav-tabs">
                <li class="active"><a  href="#mich" data-toggle="tab"><strong>Über mich</strong></a></li>
                <li><a href="#arbeit" data-toggle="tab"><strong>Über meine Arbeit</strong></a></li>
              </ul>
              <div class="tab-content" style="padding: 0px 20px 0px 20px">
                <div class="tab-pane active" id="mich">  
                </br></br>
                    <p>Mein Name ist Mai Dinh Thanh, ich bin Studentin der Wirtschaftsinformatik an der Hochschule für Wirtschaft und Recht Berlin und befinde mich in meinem Abschlusssemester. Aktuell arbeite ich an meiner Bachelor Thesis <strong>„Evaluierung von computergestütztem Brainstorming mittels Crowdsourcing“</strong>.</p>

                    <p>Zuvor habe ich bereits den Bachelor in Biologie an der Freien Universität Berlin, sowie den Master in molekularer Lebenswissenschaft an der Humboldt Universität Berlin erworben. Zusätzlich zu meinem Studium der Wirtschaftsinformatik promoviere ich derzeit auch in meiner ersten wissenschaftlichen Disziplin im <%= link_to "SPICED-Project", "http://www.spiced.eu/", :target => "_blank" %>. Ich möchte beide Disziplinen sinnvoll vereinen und die Erkenntnisse meines jetzigen Studiums auch in die Arbeit in der Biologie einbringen. Gleichzeitig bin ich durch meine akademische Vergangenheit wissenschaftlichen Anspruch gewohnt und strebe an, dass die Ergebnisse dieser Bachelorarbeit einen verwertbaren Beitrag leisten.</p>
                </div>
                <div class="tab-pane" id="arbeit">              
                  </br></br>
                  <p>In Arbeit und Privatleben begegnet jeder Mensch einer Vielzahl von Problemen und unbekannten Aufgaben. Um diese zu lösen gibt es verschiedene Ansätze. Beispielsweise kann man den analytischen Ansatz wählen und das Problem eingangs sehr genau sezieren und nur praktikable Lösungsvorschläge suchen. Ein anderer Ansatz ist der <strong>kreative, bei welchem zuerst möglichst viele Lösungsvorschläge wertungsfrei gesammelt werden</strong> um anschließend ausgewertet und geprüft zu werden. Dadurch lassen sich <strong>feste Denkmuster durchbrechen und besonders innovative Lösungen generieren</strong>. Mit diesem Ansatz beschäftigt sich auch meine Bachelorarbeit.</p>

                  <p>Ich glaube, dass viele Dinge mit Computern erleichtert werden können und will nun wissen ob auch kreative Aufgaben, welche den menschlichen Verstand erfordern von Programmen unterstützt werden können. Genauer gesagt meine ich damit die Aufgabe Brainstorming. Ich will <strong>ergründen ob ein programmgestütztes Brainstorming mit einer Vielzahl fremder Teilnehmer effektiver sein kann als das klassische Brainstorming mit einem kleinen Kreis vertrauter Teilnehmer</strong>. Zu diesem Zweck habe ich das Programm, dass Ihr auf dieser Seite findet geschrieben. Es dient dabei als Hilfe, Ideen übersichtlich zu teilen und verschiedenen Fragen und Problemen zuzuordnen. Außerdem soll es hilfreiche Techniken und Methoden vorschlagen, die beim Brainstorming zum Einsatz kommen können um den Ideenfluss zu verbessern.</p> 

                  <p>Langfristig könnte ich mir vorstellen, auch ein Bewertungssystem zu implementieren in dem die Nutzer ihre Vorschläge gegenseitig beurteilen können. Im Rahmen der Bachelorarbeit sind die Probleme vorgegeben, für welche Ideen eingegeben werden können. Natürlich sollen später die Nutzer ihre eigenen Fragen und Projekte eingeben können.   
                  </p>  
                </div>
              </div>        
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

ideamon/app/views/projects/help.html.erb

<div class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">

      <div class="page-header">          
        <h1> Help </h1>
      </div>

      <div class="col-md-3" id="leftCol">
        <div class="well">  
          <div class="panel panel-primary">
            <div class="panel-body">   
            <strong>
            <ul class="nav nav-sidebar">
              <li class="active"><%= link_to "Step by Step", projects_help_path(anchor: "step") %></li>
              <li><%= link_to "Sign-Up", projects_help_path(anchor: "sign-up") %></li>
              <li><%= link_to "Edit Profile", projects_help_path(anchor: "edit") %></li>
              <li><%= link_to "Add idea", projects_help_path(anchor: "add") %></li>
              <li><%= link_to "Umfrage", projects_help_path(anchor: "frage") %></li>
              <li><%= link_to "Logout", projects_help_path(anchor: "logout") %></li>
              <li><%= link_to "Eigene Ideen einsehen", projects_help_path(anchor: "ideen") %></li>
            </ul> 
            </strong>
            </div>
          </div>
        </div>
      </div>     

      <div class="col-md-9" id="rightCol"> 
        <div class="well"> 
          <div class="panel panel-primary">
            <h3>Step by Step</h3>
            <div class="panel-body"> 
              <div id="step">                   
                <ol><strong>
                  <li><%= link_to "Sign-Up", projects_help_path(anchor: "sign-up") %></li>
                  <li><%= link_to "Edit Profile", projects_help_path(anchor: "edit") %></li>
                  <li><%= link_to "Add idea", projects_help_path(anchor: "add") %></li>
                  <li><%= link_to "Fragebogen ausfüllen/ändern", projects_help_path(anchor: "frage") %></li>
                  <li><%= link_to "Logout", projects_help_path(anchor: "logout") %></li>
                </strong></ol>
              </div>
            </div>
          </div>
          </br>
          </br>
          <div class="panel panel-primary">
            <div class="panel-body"> 
              <h3>Hilfe</h3>
              <div id="sign-up">
                <br>
                <br>
                <h4>1. Sign-Up</h4>
                <p>Der username muss nicht Ihr tatsächlicher Name sein, sie können sich einen beliebigen Phantasienamen als virtuelle Identifikation ausdenken.</p>

                <p>Ihre E-Mail, sowie sämtliche anderen Angaben werden selbstverständlich vertraulich behandelt. Eine Weitergabe der Daten erfolgt nicht. Für die Auswertung im Rahmen der Bachelorarbeit, werden sämtliche Daten anonymisiert.</p>

                <p>Bitte wählen Sie ein sicheres Passwort mit Buchstaben, Zahlen und Sonderzeichen. Am besten notieren Sie ihr Passwort, da derzeit leider noch keine Passwortwiederherstellung implementiert ist. Administratoren können aus Sicherheitsgründen keine neuen Passwörter für Sie vergeben, da Sie selbst keinen Zugriff auf Ihre Nutzerkonten haben.</p>
              </div>

              <div id="edit">
                <br>
                <br>
                <h4>2. Edit Profile</h4>
                <p>Bitte geben Sie weitere Details zu Ihrer Person an um eine genauere Auswertung zu ermöglichen. Die Daten werden vertraulich behandelt und nur anonymisiert ausgewertet. In einigen der Felder können Sie aus einer Drop-Down Liste den zutreffenden Eintrag auswählen, bei anderen haben Sie die Möglichkeit eine freie Eingabe zu tätigen.</p>

                <p>Am Ende des Formulars wird zur Authentifizierung Ihr aktuelles Passwort benötigt</p>.
                <p>Auf der rechten Seite können Sie optional auch Ihr Passwort ändern.</p>
              </div>

              <div id="add">
                <br>
                <br>
                <h4>3. Add idea</h4>
                <p>Wählen Sie in der Navigation in der Kopfzeile den Reiter Add Ideas aus. Sie gelangen zur Projektübersicht.</p>

                <p>Nun wählen Sie bitte nacheinander Projekt 1 und später Projekt 2 aus. Sie gelangen in die jeweilige Einzelansicht.</p>

                <p>Anschließend finden Sie in der linken unteren Ecke das Fenster um neue Ideen einzutragen. Bitte beschränken Sie sich auf maximal 300 Zeichen um die Ideen übersichtlich zu halten. Vergewissern Sie sich bitte ferner, dass Sie tatsächlich eine Eingabe getätigt haben, bevor Sie die Idee speichern, da andernfalls eine Fehlermeldung ausgegeben wird. In diesem Fall können Sie einfach im Browser die „zurück“ Navigation benutzen. Wenn Sie mit einer Idee zufrieden sind betätigen Sie einfach den „Save Idea“ Button. Sie können diesen Vorgang beliebig oft wiederholen.</p>

                <p>Falls Sie Schwierigkeiten haben, eine Idee zu finden können Sie im Fenster Ideas auf den Reiter all Ideas  wechseln und sich die Ideen anderer Teilnehmer ausgeben lassen. Anschließend können Sie von diesen inspirieren lassen, diese weiterentwickeln oder kombinieren.</p>

                <p>Im Reiter my Ideas können Sie falls es tatsächlich notwendig wird auch Ihre bereits eingegebenen Ideen abändern. Klicken Sie dazu einfach auf den Text einer Ihrer Ideen. Allerdings können Sie eine geänderte Idee auch einfach als neue Idee eingeben, dies ist sogar ausdrücklich erwünscht, denn es gibt wie gesagt keine unsinnigen Ideen ;-) Diese Option ist eher zur Fehlerkorrektur angedacht.</p>

                <p>Eine weitere Inspirationsquelle finden Sie in der linken oberen Ecke. Dort werden Ihnen in einer Karussell-Box verschiedene sogenannter Kreativismen vorgeschlagen. Dabei handelt es sich um Vorschläge kreativer Vorgehensweisen um zum Beispiel Denkblockaden zu lösen oder entferntere Assoziationen ans Tageslicht zu bringen. Wenn Sie einer der Kreativismen anspricht versuchen Sie es doch einfach einmal, die Beschreibung finden Sie direkt in der Box. Falls Sie nähere Informationen wünschen wählen Sie bitte den Hauptnavigationsreiter (Kopfzeile) Kreativismen an. Dort finden Sie die Liste sämtlicher vorgeschlagener Kreativismen.</p>
              </div>

              <div id="frage">
                <br>
                <br>
                <h4>4. Umfrage</h4>
                <p>Wenn Sie für beide Projekte Ideen eingebracht haben, nehmen Sie sich doch bitte noch die Zeit, eine kurze Auswertung der Anwendung vorzunehmen. Zu diesem Zweck wählen Sie einfach den Hauptnavigationsreiter (Kopfzeile) Umfrage an. Sie werden zu einer Umfrage weitergeleitet. Diese soll helfen die Anwendung zu verbessern und die Ergebnisse die sie hervorbringt besser zu verstehen. </p>
                <p><strong> Falls sie bereits einen Fragebogen ausgefüllt haben und diesen ändern wollen, klicken sie bitte auf EDIT (dieser Button erscheint erst, wenn Sie bereits einen Fragebogen ausgefüllt haben) </strong></p>

                <% @user.questions.order(created_at: :desc).each do |question| %>
                  <%= link_to "Edit", edit_question_path(question), class: "btn btn-warning btn-sm" %>
                <% end %> 
              </div>

              <div id="logout">
                <br>
                <br>
                <h4>5. Logout</h4>
                <p>Bitte denken Sie zu Ihrer Sicherheit daran sich am Ende ihrer Sitzung abzumelden, den entsprechenden Button finden Sie oben rechts auf der Hauptnavigationsleiste (Kopfzeile).</p>
              </div> 

              <div id="ideen">
                <br>
                <br>
                <h4>6. eigene Ideen einsehen</h4>
                <p>Die Untersuchung findet in 3 Durchläufen statt. Daher können Sie Ihre Ideen nur innerhalb der angegebenen Deadline einsehen. Zwischenzeitlich besteht diese Möglichkeit nicht. Am Ende der Untersuchung können Sie Ihre Ideen aber wieder einsehen. Bitte nehmen Sie nur an einem der Durchläufe teil um die Ergebnisse nicht zu verfälschen. Eingaben in nachfolgenden Durchläufen können nicht berücksichtigt werden. </p>
              </div>
            </div>
          </div>         
        </div>
      </div>

    </div>
  </div>
</div>

ideamon/app/views/projects/index.html.erb
<div class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">

      <div class="page-header">          
        <h1>Projects</h1>
      </div>

      <div class="col-md-3" id="leftCol">
        <div class="well">
          <div class="panel panel-primary">
            <div class="panel-body">     
              <p><strong>Wählen Sie bitte einen Projekt aus, um Ideen einzugeben.</strong></p>
            </div>
          </div>
        </div>
      </div>     

      <div class="col-md-9" id="rightCol"> 
        <div class="well"> 
          <%= link_to 'New Project', new_project_path, class: "btn btn-success btn-sm" %>  
          <%= link_to 'Export XLS', url_for(:format => 'xls'), class: "btn btn-primary btn-sm" %> 
          <%= link_to 'Export CSV', url_for(:format => 'csv'), class: "btn btn-primary btn-sm" %>
        </br>
        </br>
          <div class="panel panel-primary">
            <h3>To do </br><small><%= pluralize(@todo.count, "Project") %></small></h3>
            <div class="panel-body">
              <div class="table-responsive table-scrollable">                
                <%= render partial: "projecttable", locals: {projects: @todo, css_class: "todo"} %>
              </div>
            </div>
          </div>
          </br>

          <div class="panel panel-primary">
            <h3>Done</br><small><%= pluralize(@done.count, "Project") %></small></h3>
            <div class="panel-body">
              <div class="table-responsive table-scrollable">                
                <%= render partial: "projecttable", locals: {projects: @done, css_class: "done"} %>
              </div>
            </div>
          </div>                        
        </div>
      </div>

    </div>
  </div>
</div>

ideamon/app/views/projects/index.xls.erb


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Deadline</th>
      <th>Done</th>
      <th>User</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.deadline %></td>
        <td><%= project.done %></td>
        <td><%= project.user_id %></td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

ideamon/app/views/projects/new.html.erb
<div class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">

      <div class="page-header">          
        <h1>New Project</h1>
      </div>

      <div class="col-md-3" id="leftCol">
        <div class="well">    
          
        </div>
      </div>     

      <div class="col-md-9" id="rightCol"> 
        <div class="well"> 
          <%= render 'form' %>
        </div>
      </div>

    </div>
  </div>
</div>

ideamon/app/views/projects/show.html.erb
<div class="bs-docs-section">

  <div class="row">
    <div class="col-md-12">
      <div class="col-md-9 col-md-offset-3" >
        <div class="page-header">          
          <h1><%= @project.question %></h1>
        </div>
      </div>
    </div>
  </div>        

  <div class="row">
    <div class="col-md-12">
      <div class="col-md-3" id="left_creativity">
        <div id="side_carousel">
          <%= render 'carousel_creativitycards' %>
        </div>
      </div>
      <div class="col-md-3" id="left">    
        <div id="side_input">           
          <%= render 'idea_input' %>    
        </div>
      </div>
      <div class="col-md-9 col-md-offset-3"> 
        <div class="well">
          <%= render 'info' %>
        </div> 
      </div>
    </div>
  </div>  



  <div class="row">
    <div class="col-md-12">
      <div class="col-md-9 col-md-offset-3" >  
        <div class="well">
          <h2>Ideas</h2>
          <ul class="nav nav-tabs">
            <li class="active"><a  href="#myIdeas" data-toggle="tab"><strong>my Ideas</strong></a></li>
            <li><a href="#allIdeas" data-toggle="tab"><strong>all Ideas</strong></a></li>
          </ul>
          <div class="tab-content" style="padding: 0px 20px 0px 20px">
            <div class="tab-pane active" id="myIdeas">  
                <%= render 'tab_myIdeas' %>
            </div>
            <div class="tab-pane" id="allIdeas">              
              <%= render 'tab_allIdeas' %>          
            </div>
          </div>
        </div>
      </div>            
    </div>
  </div> 


</div>