ideamon/config/routes.rb
Rails.application.routes.draw do

  resources :questions
  get "projects/home"
  get "projects/about"
  get "ideas/start"
  get "projects/help"
  get "projects/impressum"
  

  devise_for :users
  resources :creativitycards 
  resources :projects 
  resources :ideas 

   

  root 'projects#home'

end

ideamon/app/views/layouts/_messages.html.erb
<% if notice %> 
  <p id="notice" class="alert alert-success alert-dismissable fade in" data-dismiss="alert" aria-hidden="true">
    <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  </p>
<% end %>

<% if alert %> 
  <p id="notice" class="alert alert-danger alert-dismissable fade in" data-dismiss="alert" aria-hidden="true">
    <%= alert %>
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  </p>
<% end %>

ideamon/app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <%= link_to "IMon", root_path, :class => "navbar-brand" %>         
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%unless current_user.blank? -%>
        <% if current_user.admin == true %>
          <li class="link"><%= link_to "Project", projects_path %></li>  
          <li class="link"><%= link_to "Questionnaire result", questions_path %></li>
          <li class="link"><%= link_to "Ideas", ideas_path %></li> 
          <% else %>          
        <% end %> 
        <% else %>          
        <% end %> 
        
        <li class="link"><%= link_to "Add Ideas", ideas_start_path %></li>
        <li class="link"><%= link_to "Fragebogen", new_question_path %></li>
        <li class="link"><%= link_to "Kreativismen", creativitycards_path %></li> 
        <li class="link"><%= link_to "Help", projects_help_path %></li>
        <li class="link"><%= link_to "About", projects_about_path %></li> 
      </ul>

      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li>
          <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
        </li>
        <li>
          <%= link_to "Edit Profile " + current_user.username, edit_user_registration_path %>
        </li>
      <% else %>
        <li>
          <%= link_to 'Login', new_user_session_path %>
        </li>
        <li>
          <%= link_to 'Sign up', new_user_registration_path %>
        </li>
      <% end %>
      </ul>

    </div>
  </div>
</div>


ideamon/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>IMon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults, :cache => false %>
  <%= csrf_meta_tags %>

	<!--custom CSS -->

	<%= stylesheet_link_tag 'cerulean.scss' %> 
</head>
<body>
<div id="wrap">
	<div class="container">
		<%= render 'layouts/navigation' %>
		<%= render 'layouts/messages' %>
	  <%= yield %>
	</div>
</div>

<div id="footer">
  <div class="container" id="f_id">
    <p class="text-muted credit">Copyright &copy; Mai Dinh Thanh | <%= link_to "Impressum", projects_impressum_path %> | <%= link_to "Kreativismen", "http://www.kreativismen.de/", :target => "_blank" %></p>            
  </div>
</div>

</body>
</html>