ideamon/config/routes.rb
Rails.application.routes.draw do

  resources :questions
  get "projects/home"
  get "projects/about"
  get "ideas/start"
  get "projects/help"
  get "projects/impressum"
  

  devise_for :users
  resources :creativitycards 
  resources :projects 
  resources :ideas 

   

  root 'projects#home'

end

ideamon/app/models/creativitycard.rb
class Creativitycard < ActiveRecord::Base
	mount_uploader :image, ImageUploader

	belongs_to :project
	belongs_to :user
end

ideamon/app/controllers/creativitycards_controller.rb
class CreativitycardsController < ApplicationController
  before_action :set_creativitycard, only: [:show, :edit, :update, :destroy]
  before_action :set_ccard_admin_edit_destroy, only: [:show, :edit, :update, :destroy]
  before_action :set_ccard_admin_create, only: [:new, :create]
  before_action :authenticate_user!, except: [:home, :about, :help, :impressum]

  # GET /creativitycards
  # GET /creativitycards.json
  def index
    @creativitycards = Creativitycard.all.order(:title)
  end

  # GET /creativitycards/1
  # GET /creativitycards/1.json
  def show
  end

  # GET /creativitycards/new
  def new
    @creativitycard = Creativitycard.new
  end

  # GET /creativitycards/1/edit
  def edit
  end

  # POST /creativitycards
  # POST /creativitycards.json
  def create
    @creativitycard = Creativitycard.new(creativitycard_params)

    respond_to do |format|
      if @creativitycard.save
        format.html { redirect_to @creativitycard, notice: 'Creativitycard was successfully created.' }
        format.json { render :show, status: :created, location: @creativitycard }
      else
        format.html { render :new }
        format.json { render json: @creativitycard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creativitycards/1
  # PATCH/PUT /creativitycards/1.json
  def update
    respond_to do |format|
      if @creativitycard.update(creativitycard_params)
        format.html { redirect_to @creativitycard, notice: 'Creativitycard was successfully updated.' }
        format.json { render :show, status: :ok, location: @creativitycard }
      else
        format.html { render :edit }
        format.json { render json: @creativitycard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creativitycards/1
  # DELETE /creativitycards/1.json
  def destroy
    @creativitycard.destroy
    respond_to do |format|
      format.html { redirect_to creativitycards_url, notice: 'Creativitycard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creativitycard
      @creativitycard = Creativitycard.find(params[:id])
    end

    def set_ccard_admin_edit_destroy
      @creativitycard = Creativitycard.find(params[:id])
      if @creativitycard.user_id != current_user.id || current_user.admin != true
        redirect_to :back, alert: 'Only Admin are alowd to edit or delete Creativitycards.'
      end
    end

    def set_ccard_admin_create
      @creativitycard = Creativitycard.new
      
      if current_user.admin != true
        redirect_to :back, alert: 'Only Admin are alowd to create Creativitycards.'
      end
    end    

    # Never trust parameters from the scary internet, only allow the white list through.
    def creativitycard_params
      params.require(:creativitycard).permit(:title, :suggestion, :example, :shortdescription, :image, :remote_image_url, :idea_id, :project_id, :user_id)
    end
end

ideamon/app/helpers/creativitycards_helper.rb
module CreativitycardsHelper
end

ideamon/app/views/creativitycards/_form.html.erb
<%= form_for(@creativitycard, :html => {:multipart => true}) do |f| %>
  <% if @creativitycard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@creativitycard.errors.count, "error") %> prohibited this creativitycard from being saved:</h2>

      <ul>
      <% @creativitycard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div> 
   
  <div class="field">
    <%= f.label :shortdescription %><br>
    <%= f.text_area :shortdescription %>
  </div>
  <div class="field">
    <%= f.label :suggestion %><br>
    <%= f.text_area :suggestion %>
  </div>  
  <div class="field">
    <%= f.label :example %><br>
    <%= f.text_area :example %>
  </div>
  <div class="field">
    <%= f.label :"Add Image" %><br>
    <%= f.file_field :image  %>
  </div>

  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.number_field :project_id %>
  </div>

  <%= f.hidden_field :user_id, { :value => current_user.id} %> 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ideamon/app/views/creativitycards/_kreativismen.html.erb
    <div class="row">
      <div class="col-md-4">
        <div class="thumbnail" >                          
          <h3>Addieren</h3>
          <a class="menue">
            <%= image_tag ("Addieren.png") %>
            <span><%= image_tag ("Addieren.png") %></span></a>
          <p style="white-space: pre-line;">Kombinieren, verschmelzen, fusionieren. Zwei Ideen miteinander verknüpfen. Schnittpunkte finden. Schnittmenge bilden. Mischen, zusammenfügen, verbinden. Kombinieren verschiedener Schriftschnitte und -größen. Aus zwei mach eins.</p>
          <p style="white-space: pre-line;"><strong>Beispiel: </strong>Aus der Kombination zweier Sportarten (Surfen und Segelfliegen) entstand eine neue Sportart: das Kite-Surfen, bei dem der Sportler auf einem Surfbrett stehend einen Kite (Lenkdrachen) zur Fortbewegung verwendet.</p>
        </div>                  
      </div>

      <div class="col-md-4">
        <div class="thumbnail" >  
          <h3>Analogie</h3>
          <a class="menue">
            <%= image_tag ("Analogie.png") %>
            <span><%= image_tag ("Analogie.png") %></span></a>
          <p style="white-space: pre-line;">Anwendung ähnlicher Prinzipien. Vergleiche ziehen. Funktionsgleiche Strukturen übernehmen. Vorbilder suchen. Nachmachen. Metaphern finden. Genauso, wie …</p>
          <p style="white-space: pre-line;"><strong>Beispiel: </strong> In der Bionik finden sich unzählige Beispiele für Analogien: Prinzipien aus der Natur werden übernommen und auf andere Bereiche übertragen. So besitzt beispielsweise die Klette (Arctium lappa) Früchte mit Borsten, deren Spitzen winzige elastische Häkchen tragen. Hieraus wurde der praktische Klettverschluss entwickelt.</p>
        </div>                  
      </div>

      <div class="col-md-4">
        <div class="thumbnail" >  
          <h3>Entgeneralisierer</h3>
          <a class="menue">
            <%= image_tag ("Entgeneralisierer.png") %>
            <span><%= image_tag ("Entgeneralisierer.png") %></span></a>
          <p style="white-space: pre-line;">Paradigmenwechsel. Vorurteile aufheben. Nicht verallgemeinern. Kann man etwas, das schon immer so war, auch anders machen? Entgegen dem Trend. Antizyklisch. Nicht so denken, wie alle anderen. Mit den Regeln brechen. Gegebenes in Frage stellen. Etwas auf den Punkt bringen.</p>
          <p style="white-space: pre-line;"><strong>Beispiel: </strong>In den 1980er Jahren gab es praktisch nur zwei Sorten von Uhren: teure Luxusuhren und gleichförmige asiatische Billiguhren mit digitaler Anzeige. Eine schweizer Firma stellte diesen Trend in Frage und entwickelte eine individuelle und dennoch preiswerte Designuhr – die Swatch.</p>
        </div>                  
      </div>
    </div>

    <div class="row">    
      <div class="col-md-4">
        <div class="thumbnail" >  
          <h3>Extrem</h3>
          <a class="menue">
            <%= image_tag ("Extrem.png") %>
            <span><%= image_tag ("Extrem.png") %></span></a>
          <p style="white-space: pre-line;">Übertreiben. Bestehende Merkmale ins Extreme ziehen: extrem groß, klein, fett, dünn, hässlich, bunt, schlicht, süß, schnell, schief, hell, weich. Wie weit kann man die Idee treiben? Mut zu extremen Ideen. Gegen alle Regeln verstoßen. Extreme Farbkombinationen oder Typo--Experimente. Extreme Wortwahl. Provozieren.</p>
          <p style="white-space: pre-line;"><strong>Beispiel: </strong>Amerikanische Produkte gelten bisweilen als Inbegriff des Extrems: Alles ist XXLarge, sei es der „Supersize BigMac“ oder der „Hummer“ – ein überdimensionierter Geländewagen. Der Erfolg gibt dem Extrem Recht.</p>
        </div>                  
      </div>        

      <div class="col-md-4">
        <div class="thumbnail" >  
          <h3>Fokus</h3>
          <a class="menue">
            <%= image_tag ("Fokus.png") %>
            <span><%= image_tag ("Fokus.png") %></span></a>
          <p style="white-space: pre-line;">Akzente setzen. Fokus verlagern. Sowohl optisch als auch inhaltlich. Was ist das Zentrum des Problems? Zweitnutzen. Grafischen Fokus andeuten. Aus der Mitte rücken. Exzenter. Sich auf das Wesentliche konzentrieren.</p>
          <p style="white-space: pre-line;"><strong>Beispiel: </strong>Vilfredo Pareto (Ökonom aus dem 19. Jahrhundert) entdeckte die so genannte 80/20- Regel (auch Pareto-Prinzip). Diese besagt, dass 80 % des Geschehens durch 20 % der Beteiligten verursacht werden. So erwirtschaften beispielsweise 20 % der Kunden 80 % des Gewinns, oder werden 80 % der Arbeit in 20 % der Zeit erledigt. Merke: fokussiere dich auf die wesentlichen Dinge.</p>
        </div>                  
      </div>


      <div class="col-md-4">
        <div class="thumbnail" >   
          <h3>Fragment</h3>
          <a class="menue">
            <%= image_tag ("Fragment.png") %>
            <span><%= image_tag ("Fragment.png") %></span></a>
          <p style="white-space: pre-line;">Problem in Teilprobleme zerlegen, diese einzeln bearbeiten, später zusammenfügen. Zersplittern, zerbrechen, fallen lassen. Explosionszeichnung. Einzelteile neu kombinieren oder Fragment als Ganzes betrachten. Teile des Objekts entfernen. Fragmente aneinanderreihen. Muster, Abspaltung, Spin-Off.</p>
          <p style="white-space: pre-line;"><strong>Beispiel: </strong>Das SZ-Magazin der Süddeutschen Zeitung (Nr. 51, 2005) gab zwei Varianten zum Thema „Zwillinge“ heraus. Der Leser bekam jeweils nur die Geschichte eines Zwillings – also nur einen Teil des Ganzen zu lesen. 15.000 Hefte wurden nachbestellt. Im Gegensatz zum → Modul ist das Fragment ein Bruchteil, kein Baustein.</p>
        </div>                  
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <div class="thumbnail" >  
          <h3>Modify</h3>
          <a class="menue">
            <%= image_tag ("Modify.png") %>
            <span><%= image_tag ("Modify.png") %></span></a>
          <p style="white-space: pre-line;">Wie verändert sich dadurch der Charakter, die Funktion des Objekts? Transformieren: verdrehen, verkleinern, vergrößern, verzerren. Optisch und inhaltlich verändern. Dehnen, strecken, neigen. Verschönern?</p>
          <p style="white-space: pre-line;"><strong>Beispiel: </strong>Die Firma Heinz brachte im Jahr 2000 unterschiedlich eingefärbte Ketchup-Sorten auf den Markt. Das bunte Ketchup brachte einen Umsatzgewinn von 12 % in Haushalten mit Kindern.</p>
        </div>                  
      </div>

      <div class="col-md-4">
        <div class="thumbnail" >  
          <h3>Perspektive</h3>
          <a class="menue">
            <%= image_tag ("Perspektive.png") %>
            <span><%= image_tag ("Perspektive.png") %></span></a>
          <p style="white-space: pre-line;">Standpunkt wechseln. Neue Sicht auf die Dinge. Auf den Kopf stellen. Sich auf den Boden legen. Objekt von unten oder ganz oben betrachten. Nicht nur den eigenen Standpunkt bedenken. In andere hineinversetzen. Ungewohnte, extreme oder falsche Perspektive erzeugen.</p>
          <p style="white-space: pre-line;"><strong>Beispiel: </strong>Jahrelang versuchte das US-Militär vergeblich ein Flugzeug zu entwickeln, das vom Radar nicht erkannt wird. Erst als sie das Problem aus einem anderen Blickwinkel betrachteten, gelang ihnen das Kunststück: Anstatt ein Flugzeug entsprechend zu verändern, entwickelten zunächst ein für das Radar unsichtbares Objekt, um sich anschließend dem Problem zu widmen, dieses zum Fliegen zu bringen. So entstand der Stealth Bomber.</p>
        </div>                  
      </div>

      <div class="col-md-4">
        <div class="thumbnail" >  
          <h3>Prognose</h3>
          <a class="menue">
            <%= image_tag ("Prognose.png") %>
            <span><%= image_tag ("Prognose.png") %></span></a>
          <p style="white-space: pre-line;">Was bringt die Zukunft? Risiken und Chancen antizipieren. Welche Entwicklungen wird es geben? Diesen voraus sein. Oder entgegen den Trends agieren, sich abheben. Welche Produkte wird man in 10, 50, 100 Jahren haben? Und welche nicht mehr?</p>
          <p style="white-space: pre-line;"><strong>Beispiel: </strong>1993 las Jeff Bezos eine Statistik, nach der das Internet in den kommenden Jahren eine Wachstumsrate von 2300 % pro Jahr erfahren sollte. Sofort machte er eine Liste, welche Produkte er über das Internet verkaufen könnte. Am Ende entschied er sich für Bücher und gründete Amazon, eines der ersten milliardenschweren Dotcom-Unternehmen.</p>
        </div>                  
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <div class="thumbnail" >  
          <h3>Reduce</h3>
          <a class="menue">
            <%= image_tag ("Reduce.png") %>
            <span><%= image_tag ("Reduce.png") %></span></a>
          <p style="white-space: pre-line;">Weniger ist mehr. </p>
          <p style="white-space: pre-line;"><strong>Beispiel: </strong>Apples iPod hat gerade wegen seines puristischen Designs und der Monofunktionalität (kann nur Musik abspielen, sonst nichts) einen riesigen Erfolg und ist eines der meistverkauften Produkte der letzten Jahre.</p>
        </div>                  
      </div>

      <div class="col-md-4">
        <div class="thumbnail" >  
          <h3>Szenario</h3>
          <a class="menue">
            <%= image_tag ("Szenario.png") %>
            <span><%= image_tag ("Szenario.png") %></span></a>
          <p style="white-space: pre-line;">Objekt in einen inhaltlichen Kontext setzen. Wo wird es von wem und wie verwendet? Storyboard zeichnen. Eine Geschichte um das Objekt erfinden. Das Produkt zum Leben erwecken, ihm einen Charakter geben. Was wäre wenn … ?</p>
          <p style="white-space: pre-line;"><strong>Beispiel: </strong>Während der Apollo-Missionen baute die NASA am Boden stets eine exakte Nachbildung der Raumkapsel im All. So konnten Problemfälle simultan nachgespielt und Lösungen mit den gleichen Werkzeugen und Materialien, die den Astronauten zur Verfügung standen, erarbeitet werden.</p>
        </div>                  
      </div>

      <div class="col-md-4">
        <div class="thumbnail" >  
          <h3>Transfer</h3>
          <a class="menue">
            <%= image_tag ("Transfer.png") %>
            <span><%= image_tag ("Transfer.png") %></span></a>
          <p style="white-space: pre-line;">Transfer in anderen Kontext, andere Kultur oder andere Epoche. Existiert das Problem auch in anderen Bereichen? Gab’s das schon mal oder so ähnlich? Idee auf anderen Ort, andere Situation übertragen. Eine Lösung speichern und auf andere Probleme anwenden. Innerhalb eines Mediums bleiben oder zwischen den Disziplinen wechseln. Parallelen finden.</p>
          <p style="white-space: pre-line;"><strong>Beispiel: </strong>Die britische easyGroup betreibt eine Vielzahl von Subunternehmen, die alle auf dem gleichen Reduce-Konzept basieren. Dieses wurde eins-zu-eins auf andere Geschäftsbereiche übertragen. So gibt es das easyInternetcafé, easyCar Autovermietungen, easyHotels oder easyCruise Kreuzfahrten.</p>
        </div>                  
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <div class="thumbnail" >  
          <h3>Variation</h3>
          <a class="menue">
            <%= image_tag ("Variation.png") %>
            <span><%= image_tag ("Variation.png") %></span></a>
          <p style="white-space: pre-line;">Alternativen finden. Welche Optionen gibt es? Von einer Idee ausgehend verschiedene Varianten ableiten. Der beste Weg zu einer guten Idee zu kommen ist: viele Ideen zu produzieren. In kleinen Schritten von der Ausgangsidee entfernen, jeweils nur eine Kleinigkeit, einen Parameter ändern. Im Gegensatz zur Reihe entstehen keine eigenständigen Objekte, sondern Varianten einer einzelnen Idee.</p>
          <p style="white-space: pre-line;"><strong>Beispiel: </strong>Das Prinzip des Glühfadens ist bereits seit Anfang des 19. Jahrhunderts bekannt. Doch erst 1879 entwickelte Thomas Edison in unzähligen Experimenten mit verschiedensten Materialien eine leuchtfähige Glühlampe, die industriell hergestellt werden konnte. Hierfür baute er hunderte von Prototypen mit jeweils geringfügigen Variationen, bis er die perfekte Technik gefunden hatte. Im Gegensatz zur Reihe entstehen keine eigenständigen Objekte, sondern Varianten einer einzelnen Idee.</p>
        </div>                  
      </div>                                                

      <div class="col-md-4">
        <div class="thumbnail" >  
          <h3>Zoom</h3>
          <a class="menue">
            <%= image_tag ("Zoom.png") %>
            <span><%= image_tag ("Zoom.png") %></span></a>
          <p style="white-space: pre-line;">Zoom in and out. Vom Kleinen ins Große ins Kleine. Ist die Idee skalierbar? Details betrachten. Inhaltlichen Kontext ausweiten. Rolle des Kleinen in der größeren Umgebung betrachten. Miniaturisieren, vergrößern, hochkopieren. Objekt zoomen, aufblähen oder schrumpfen.</p>
          <p style="white-space: pre-line;"><strong>Beispiel: </strong>Polaroid-Kameras waren jahrelang ein Nischenprodukt, da niemand die klobigen Geräte gerne mit sich herum schleppte. Durch eine radikale Verkleinerung wurde eine neue Zielgruppe gewonnen: Die viel kleinere „iZone“ produziert Sofortbilder im Sticker-Format und spricht besonders Teenager an.</p>
        </div>                  
      </div>
    </div>

ideamon/app/views/creativitycards/edit.html.erb
<h1>Editing Creativitycard</h1>

<%= render 'form' %>

<%= link_to 'Show', @creativitycard %> |
<%= link_to 'Back', creativitycards_path %>

ideamon/app/views/creativitycards/index.html.erb
<div class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">          
        <h1>Kreativismen</h1>
      </div>
    </div>
  </div>
      
  <div class="row">
    <div class="col-md-12">


      <% if current_user.admin == true %>
      <%= link_to 'New Creativitycard', new_creativitycard_path, class: "btn btn-success btn-sm" %>
      <% else %>
      <% end %>
      <br>
      <br>

      <!-- <% @creativitycards.order(created_at: :desc).each do |c| %>
        <div class="col-md-4">
          <div class="thumbnail" >                          
            <h3><%= link_to c.title, creativitycard_path(c) %></h3>

            <a class="menue">
              <%= image_tag c.image_url(:thumb) if c.image? %>
              <span><%= image_tag c.image_url(:normal) if c.image? %></span></a>

            <p style="white-space: pre-line;"><%= c.suggestion %></p>
            <p style="white-space: pre-line;"><strong>Beispiel: </strong><%= c.example %></p>
            <% if current_user.admin == true %>
              <%= link_to 'Show', c, class: "btn btn-primary btn-sm" %> 
              <%= link_to 'Edit', edit_creativitycard_path(c), class: "btn btn-warning btn-sm" %> 
              <%= link_to 'Destroy', c, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
            <% else %>
            <% end %>
          </div>                  
        </div>
      <% end %> -->

      <%= render "kreativismen" %>

    </div>
  </div>
</div>

ideamon/app/views/creativitycards/new.html.erb
<h1>New Creativitycard</h1>

<%= render 'form' %>

<%= link_to 'Back', creativitycards_path %>

ideamon/app/views/creativitycards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @creativitycard.title %>
</p>

<p>
  <strong>Short description:</strong>
  <%= @creativitycard.shortdescription %>
</p>

<p>
  <strong>Suggestion:</strong>
  <%= @creativitycard.suggestion %>
</p>

<p>
  <strong>Example:</strong>
  <%= @creativitycard.example %>
</p>

<%= image_tag @creativitycard.image_url if @creativitycard.image? %>

<p>
  <strong>Project:</strong>
  <%= @creativitycard.project.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @creativitycard.user.username %>
</p>


<%= link_to 'Edit', edit_creativitycard_path(@creativitycard) %> |
<%= link_to 'Back', creativitycards_path %>